# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/home.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1174, 625)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("background-color: black;\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.main_widget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.main_widget.setGeometry(QtCore.QRect(70, 0, 1081, 491))
        self.main_widget.setObjectName("main_widget")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.label_3 = QtWidgets.QLabel(parent=self.home)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 211, 41))
        self.label_3.setStyleSheet("border: none;\n"
"background: none;\n"
"font: 20pt \"Segoe Print\";")
        self.label_3.setObjectName("label_3")
        self.label_26 = QtWidgets.QLabel(parent=self.home)
        self.label_26.setGeometry(QtCore.QRect(1050, 910, 121, 16))
        self.label_26.setStyleSheet("color: rgb(131, 131, 131);\n"
"background-color: none\n"
"")
        self.label_26.setObjectName("label_26")
        self.label_28 = QtWidgets.QLabel(parent=self.home)
        self.label_28.setGeometry(QtCore.QRect(1320, 800, 121, 16))
        self.label_28.setStyleSheet("color: rgb(131, 131, 131);\n"
"background-color: none\n"
"")
        self.label_28.setObjectName("label_28")
        self.label_30 = QtWidgets.QLabel(parent=self.home)
        self.label_30.setGeometry(QtCore.QRect(1070, 840, 121, 16))
        self.label_30.setStyleSheet("color: rgb(131, 131, 131);\n"
"background-color: none\n"
"")
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(parent=self.home)
        self.label_31.setGeometry(QtCore.QRect(1370, 860, 121, 16))
        self.label_31.setStyleSheet("color: rgb(131, 131, 131);\n"
"background-color: none\n"
"")
        self.label_31.setObjectName("label_31")
        self.label_13 = QtWidgets.QLabel(parent=self.home)
        self.label_13.setGeometry(QtCore.QRect(0, 20, 1071, 471))
        self.label_13.setStyleSheet("background-color: rgb(45, 45, 45);\n"
"    height: 50px; \n"
"    width: 100%; \n"
"border-radius: 20px;")
        self.label_13.setText("")
        self.label_13.setScaledContents(True)
        self.label_13.setWordWrap(False)
        self.label_13.setObjectName("label_13")
        self.horizontalWidget = QtWidgets.QWidget(parent=self.home)
        self.horizontalWidget.setGeometry(QtCore.QRect(310, 30, 351, 45))
        self.horizontalWidget.setStyleSheet("background: none")
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_search = QtWidgets.QPushButton(parent=self.horizontalWidget)
        self.btn_search.setStyleSheet("border: none;\n"
"background: none;")
        self.btn_search.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/magnifying-glass-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_search.setIcon(icon)
        self.btn_search.setObjectName("btn_search")
        self.horizontalLayout_3.addWidget(self.btn_search)
        self.txt_search = QtWidgets.QLineEdit(parent=self.horizontalWidget)
        self.txt_search.setStyleSheet("width: 100%;\n"
"  padding: 10px;\n"
"  font-size: 14px;\n"
"  border: 1px solid #B3B3B3; \n"
"  border-radius: 15px; \n"
"  background-color: transparent;\n"
"  color: rgb(0, 0, 0)")
        self.txt_search.setFrame(True)
        self.txt_search.setObjectName("txt_search")
        self.horizontalLayout_3.addWidget(self.txt_search)
        self.song_container = QtWidgets.QWidget(parent=self.home)
        self.song_container.setGeometry(QtCore.QRect(19, 99, 1021, 371))
        self.song_container.setObjectName("song_container")
        self.label_13.raise_()
        self.label_3.raise_()
        self.label_26.raise_()
        self.label_28.raise_()
        self.label_30.raise_()
        self.label_31.raise_()
        self.horizontalWidget.raise_()
        self.song_container.raise_()
        self.main_widget.addWidget(self.home)
        self.playlist = QtWidgets.QWidget()
        self.playlist.setObjectName("playlist")
        self.label_27 = QtWidgets.QLabel(parent=self.playlist)
        self.label_27.setGeometry(QtCore.QRect(10, 20, 1061, 461))
        self.label_27.setStyleSheet("background-color: rgb(45, 45, 45); /* Màu đen */\n"
"    height: 50px; /* Chiều cao của thanh */\n"
"    width: 100%; /* Chiều rộng của thanh */\n"
"border-radius: 20px;")
        self.label_27.setText("")
        self.label_27.setScaledContents(True)
        self.label_27.setWordWrap(False)
        self.label_27.setObjectName("label_27")
        self.label_29 = QtWidgets.QLabel(parent=self.playlist)
        self.label_29.setGeometry(QtCore.QRect(40, 40, 211, 61))
        self.label_29.setStyleSheet("font: 26pt \"Segoe Print\";\n"
"background-color: none\n"
"")
        self.label_29.setObjectName("label_29")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.playlist)
        self.pushButton_7.setGeometry(QtCore.QRect(250, 50, 51, 51))
        self.pushButton_7.setStyleSheet("border: none;\n"
"background: none")
        self.pushButton_7.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/circle-play-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_7.setIcon(icon1)
        self.pushButton_7.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_7.setObjectName("pushButton_7")
        self.playlist_container = QtWidgets.QWidget(parent=self.playlist)
        self.playlist_container.setGeometry(QtCore.QRect(40, 100, 1001, 361))
        self.playlist_container.setObjectName("playlist_container")
        self.main_widget.addWidget(self.playlist)
        self.account = QtWidgets.QWidget()
        self.account.setObjectName("account")
        self.label_4 = QtWidgets.QLabel(parent=self.account)
        self.label_4.setGeometry(QtCore.QRect(470, 20, 151, 51))
        self.label_4.setStyleSheet("background-color: none;\n"
"font: 700 30pt \"Microsoft JhengHei UI\";\n"
"color: rgb(255, 255, 255)")
        self.label_4.setObjectName("label_4")
        self.txt_name = QtWidgets.QLineEdit(parent=self.account)
        self.txt_name.setGeometry(QtCore.QRect(300, 90, 221, 41))
        self.txt_name.setStyleSheet("width: 100%;\n"
"  padding: 10px;\n"
"  font-size: 14px;\n"
"  border: 1px solid #B3B3B3; \n"
"  border-radius: 20px; \n"
"background-color: rgb(255, 255, 255);\n"
"  color: rgb(0, 0, 0)")
        self.txt_name.setObjectName("txt_name")
        self.label_5 = QtWidgets.QLabel(parent=self.account)
        self.label_5.setGeometry(QtCore.QRect(80, 90, 111, 41))
        self.label_5.setStyleSheet("font: 14pt \"Segoe Print\";\n"
"background-color: none;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.account)
        self.label_6.setGeometry(QtCore.QRect(80, 130, 131, 91))
        self.label_6.setStyleSheet("font: 14pt \"Segoe Print\";\n"
"background-color: none;\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.account)
        self.label_7.setGeometry(QtCore.QRect(80, 220, 111, 41))
        self.label_7.setStyleSheet("font: 14pt \"Segoe Print\";\n"
"background-color: none;\n"
"")
        self.label_7.setObjectName("label_7")
        self.txt_email = QtWidgets.QLineEdit(parent=self.account)
        self.txt_email.setGeometry(QtCore.QRect(300, 160, 221, 41))
        self.txt_email.setStyleSheet("width: 100%;\n"
"  padding: 10px;\n"
"  font-size: 14px;\n"
"  border: 1px solid #B3B3B3; \n"
"  border-radius: 20px; \n"
"background-color: rgb(255, 255, 255);\n"
"  color: rgb(0, 0, 0)")
        self.txt_email.setObjectName("txt_email")
        self.label_8 = QtWidgets.QLabel(parent=self.account)
        self.label_8.setGeometry(QtCore.QRect(10, 20, 1001, 471))
        self.label_8.setStyleSheet("background-color: rgb(45, 45, 45); /* Màu đen */\n"
"    height: 50px; /* Chiều cao của thanh */\n"
"    width: 100%; /* Chiều rộng của thanh */\n"
"border-radius: 20px;")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.btn_upload = QtWidgets.QPushButton(parent=self.account)
        self.btn_upload.setGeometry(QtCore.QRect(870, 300, 41, 41))
        self.btn_upload.setStyleSheet("border-radius: 20px;\n"
"background: white;\n"
"")
        self.btn_upload.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/upload-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_upload.setIcon(icon2)
        self.btn_upload.setIconSize(QtCore.QSize(16, 18))
        self.btn_upload.setObjectName("btn_upload")
        self.label_12 = QtWidgets.QLabel(parent=self.account)
        self.label_12.setGeometry(QtCore.QRect(80, 290, 111, 41))
        self.label_12.setStyleSheet("font: 14pt \"Segoe Print\";\n"
"background-color: none;\n"
"")
        self.label_12.setObjectName("label_12")
        self.txt_gender = QtWidgets.QComboBox(parent=self.account)
        self.txt_gender.setGeometry(QtCore.QRect(300, 290, 221, 41))
        self.txt_gender.setStyleSheet("width: 100%;\n"
"  padding: 10px;\n"
"  font-size: 14px;\n"
"  border: 1px solid #B3B3B3; \n"
"  border-radius: 20px; \n"
"background-color: rgb(255, 255, 255);\n"
"  color: rgb(0, 0, 0)")
        self.txt_gender.setObjectName("txt_gender")
        self.txt_gender.addItem("")
        self.txt_gender.addItem("")
        self.txt_gender.addItem("")
        self.txt_gender.addItem("")
        self.txt_dob = QtWidgets.QDateEdit(parent=self.account)
        self.txt_dob.setGeometry(QtCore.QRect(300, 220, 221, 41))
        self.txt_dob.setStyleSheet("width: 100%;\n"
"  padding: 10px;\n"
"  font-size: 14px;\n"
"  border: 1px solid #B3B3B3; \n"
"  border-radius: 20px; \n"
"background-color: rgb(255, 255, 255);\n"
"  color: rgb(0, 0, 0)")
        self.txt_dob.setObjectName("txt_dob")
        self.lb_avatar = QtWidgets.QLabel(parent=self.account)
        self.lb_avatar.setGeometry(QtCore.QRect(620, 80, 241, 261))
        self.lb_avatar.setStyleSheet("border-radius: 30px;\n"
"background: white;\n"
"")
        self.lb_avatar.setText("")
        self.lb_avatar.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/user-solid.svg"))
        self.lb_avatar.setScaledContents(True)
        self.lb_avatar.setObjectName("lb_avatar")
        self.btn_save = QtWidgets.QPushButton(parent=self.account)
        self.btn_save.setGeometry(QtCore.QRect(460, 370, 80, 24))
        self.btn_save.setObjectName("btn_save")
        self.label_8.raise_()
        self.label_4.raise_()
        self.txt_name.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.txt_email.raise_()
        self.btn_upload.raise_()
        self.label_12.raise_()
        self.txt_gender.raise_()
        self.txt_dob.raise_()
        self.lb_avatar.raise_()
        self.btn_save.raise_()
        self.main_widget.addWidget(self.account)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 51, 471))
        self.label_2.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"    height: 50px; \n"
"    width: 100%;\n"
"border-radius: 20px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 500, 1131, 121))
        self.widget.setStyleSheet("background-color: rgb(59, 59, 59)")
        self.widget.setObjectName("widget")
        self.lbl_curr_img = QtWidgets.QLabel(parent=self.widget)
        self.lbl_curr_img.setGeometry(QtCore.QRect(30, 30, 70, 70))
        self.lbl_curr_img.setAutoFillBackground(False)
        self.lbl_curr_img.setText("")
        self.lbl_curr_img.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/ab67616d0000b27343076111d560c6aec19bac01.jpg"))
        self.lbl_curr_img.setScaledContents(True)
        self.lbl_curr_img.setObjectName("lbl_curr_img")
        self.lbl_curr_artist = QtWidgets.QLabel(parent=self.widget)
        self.lbl_curr_artist.setGeometry(QtCore.QRect(110, 60, 121, 16))
        self.lbl_curr_artist.setStyleSheet("color: rgb(131, 131, 131);")
        self.lbl_curr_artist.setObjectName("lbl_curr_artist")
        self.lbl_curr_name = QtWidgets.QLabel(parent=self.widget)
        self.lbl_curr_name.setGeometry(QtCore.QRect(110, 40, 91, 16))
        self.lbl_curr_name.setStyleSheet("color: rgb(255, 255, 255)")
        self.lbl_curr_name.setObjectName("lbl_curr_name")
        self.btn_volume = QtWidgets.QPushButton(parent=self.widget)
        self.btn_volume.setGeometry(QtCore.QRect(890, 60, 21, 24))
        self.btn_volume.setStyleSheet("border: none;\n"
"background: none\n"
"")
        self.btn_volume.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/volume-high-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_volume.setIcon(icon3)
        self.btn_volume.setObjectName("btn_volume")
        self.slider_volume = QtWidgets.QSlider(parent=self.widget)
        self.slider_volume.setGeometry(QtCore.QRect(920, 60, 121, 20))
        self.slider_volume.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider_volume.setObjectName("slider_volume")
        self.slider_duration = QtWidgets.QSlider(parent=self.widget)
        self.slider_duration.setGeometry(QtCore.QRect(320, 70, 441, 20))
        self.slider_duration.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider_duration.setObjectName("slider_duration")
        self.lbl_time = QtWidgets.QLabel(parent=self.widget)
        self.lbl_time.setGeometry(QtCore.QRect(240, 70, 71, 16))
        self.lbl_time.setText("")
        self.lbl_time.setObjectName("lbl_time")
        self.btn_play = QtWidgets.QPushButton(parent=self.widget)
        self.btn_play.setGeometry(QtCore.QRect(550, 30, 21, 16))
        self.btn_play.setStyleSheet("border: none;\n"
"background: none")
        self.btn_play.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/play-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_play.setIcon(icon4)
        self.btn_play.setObjectName("btn_play")
        self.btn_next_song = QtWidgets.QPushButton(parent=self.widget)
        self.btn_next_song.setGeometry(QtCore.QRect(640, 30, 21, 20))
        self.btn_next_song.setStyleSheet("border: none;\n"
"background: none")
        self.btn_next_song.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/forward-step-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_next_song.setIcon(icon5)
        self.btn_next_song.setObjectName("btn_next_song")
        self.btn_prev_song = QtWidgets.QPushButton(parent=self.widget)
        self.btn_prev_song.setGeometry(QtCore.QRect(460, 30, 16, 16))
        self.btn_prev_song.setStyleSheet("border: none;\n"
"background: none")
        self.btn_prev_song.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/backward-step-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_prev_song.setIcon(icon6)
        self.btn_prev_song.setObjectName("btn_prev_song")
        self.verticalWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalWidget.setGeometry(QtCore.QRect(20, 30, 41, 111))
        self.verticalWidget.setStyleSheet("background-color: none")
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_nav_account = QtWidgets.QPushButton(parent=self.verticalWidget)
        self.btn_nav_account.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_nav_account.setStyleSheet("background: white;\n"
" border-radius: 15px;")
        self.btn_nav_account.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/user-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_nav_account.setIcon(icon7)
        self.btn_nav_account.setIconSize(QtCore.QSize(16, 16))
        self.btn_nav_account.setObjectName("btn_nav_account")
        self.verticalLayout_2.addWidget(self.btn_nav_account)
        self.btn_nav_home = QtWidgets.QPushButton(parent=self.verticalWidget)
        self.btn_nav_home.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_nav_home.setStyleSheet("background: white;\n"
" border-radius: 15px\n"
"")
        self.btn_nav_home.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/house-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_nav_home.setIcon(icon8)
        self.btn_nav_home.setObjectName("btn_nav_home")
        self.verticalLayout_2.addWidget(self.btn_nav_home)
        self.btn_nav_playlist = QtWidgets.QPushButton(parent=self.verticalWidget)
        self.btn_nav_playlist.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_nav_playlist.setStyleSheet("background: white;\n"
" border-radius: 15px\n"
"")
        self.btn_nav_playlist.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/list-solid123.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_nav_playlist.setIcon(icon9)
        self.btn_nav_playlist.setObjectName("btn_nav_playlist")
        self.verticalLayout_2.addWidget(self.btn_nav_playlist)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.main_widget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Popular Songs"))
        self.label_26.setText(_translate("MainWindow", "Puppy & Dangrangto"))
        self.label_28.setText(_translate("MainWindow", "Puppy & Dangrangto"))
        self.label_30.setText(_translate("MainWindow", "Puppy & Dangrangto"))
        self.label_31.setText(_translate("MainWindow", "Puppy & Dangrangto"))
        self.label_29.setText(_translate("MainWindow", "My playlist"))
        self.label_4.setText(_translate("MainWindow", "Profile"))
        self.txt_name.setPlaceholderText(_translate("MainWindow", "Name"))
        self.label_5.setText(_translate("MainWindow", "Name:"))
        self.label_6.setText(_translate("MainWindow", "Email:"))
        self.label_7.setText(_translate("MainWindow", "Birthday:"))
        self.txt_email.setPlaceholderText(_translate("MainWindow", "Email"))
        self.label_12.setText(_translate("MainWindow", "Gender:"))
        self.txt_gender.setItemText(0, _translate("MainWindow", "None"))
        self.txt_gender.setItemText(1, _translate("MainWindow", "Male"))
        self.txt_gender.setItemText(2, _translate("MainWindow", "Female"))
        self.txt_gender.setItemText(3, _translate("MainWindow", "Other"))
        self.txt_dob.setDisplayFormat(_translate("MainWindow", "d/M/yy"))
        self.btn_save.setText(_translate("MainWindow", "Save"))
        self.lbl_curr_artist.setText(_translate("MainWindow", "Puppy, Dangrangto"))
        self.lbl_curr_name.setText(_translate("MainWindow", "Wrong times"))
