# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/home.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1133, 626)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("background-color: black;\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.main_widget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.main_widget.setGeometry(QtCore.QRect(70, 0, 1011, 491))
        self.main_widget.setObjectName("main_widget")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.home)
        self.lineEdit_5.setGeometry(QtCore.QRect(60, 10, 371, 31))
        self.lineEdit_5.setStyleSheet("width: 100%;\n"
"  padding: 10px;\n"
"  font-size: 14px;\n"
"  border: 1px solid #B3B3B3; \n"
"  border-radius: 15px; \n"
"  background-color: transparent;\n"
"  color: rgb(0, 0, 0)")
        self.lineEdit_5.setFrame(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label = QtWidgets.QLabel(parent=self.home)
        self.label.setGeometry(QtCore.QRect(30, 20, 20, 20))
        self.label.setStyleSheet("background: none;\n"
"border: none;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/magnifying-glass-solid.svg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=self.home)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 211, 41))
        self.label_3.setStyleSheet("border: none;\n"
"background: none;\n"
"font: 20pt \"Segoe Print\";")
        self.label_3.setObjectName("label_3")
        self.label_14 = QtWidgets.QLabel(parent=self.home)
        self.label_14.setGeometry(QtCore.QRect(50, 120, 141, 141))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/unnamed.jpg"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(parent=self.home)
        self.label_15.setGeometry(QtCore.QRect(260, 120, 141, 141))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/anhnhac.jpg"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.label_17 = QtWidgets.QLabel(parent=self.home)
        self.label_17.setGeometry(QtCore.QRect(680, 120, 141, 141))
        self.label_17.setAutoFillBackground(False)
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/ab67616d0000b27343076111d560c6aec19bac01.jpg"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.label_16 = QtWidgets.QLabel(parent=self.home)
        self.label_16.setGeometry(QtCore.QRect(470, 120, 141, 141))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/anhnhac3.jpg"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.label_18 = QtWidgets.QLabel(parent=self.home)
        self.label_18.setGeometry(QtCore.QRect(70, 270, 81, 16))
        self.label_18.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(parent=self.home)
        self.label_19.setGeometry(QtCore.QRect(720, 270, 71, 16))
        self.label_19.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(parent=self.home)
        self.label_20.setGeometry(QtCore.QRect(530, 270, 21, 16))
        self.label_20.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(parent=self.home)
        self.label_21.setGeometry(QtCore.QRect(300, 270, 61, 16))
        self.label_21.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(parent=self.home)
        self.label_22.setGeometry(QtCore.QRect(700, 290, 121, 16))
        self.label_22.setStyleSheet("color: rgb(131, 131, 131);\n"
"background-color: none\n"
"")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(parent=self.home)
        self.label_23.setGeometry(QtCore.QRect(490, 290, 121, 16))
        self.label_23.setStyleSheet("color: rgb(131, 131, 131);\n"
"background-color: none\n"
"")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(parent=self.home)
        self.label_24.setGeometry(QtCore.QRect(300, 290, 121, 16))
        self.label_24.setStyleSheet("color: rgb(131, 131, 131);\n"
"background-color: none\n"
"")
        self.label_24.setObjectName("label_24")
        self.label_26 = QtWidgets.QLabel(parent=self.home)
        self.label_26.setGeometry(QtCore.QRect(1050, 910, 121, 16))
        self.label_26.setStyleSheet("color: rgb(131, 131, 131);\n"
"background-color: none\n"
"")
        self.label_26.setObjectName("label_26")
        self.label_28 = QtWidgets.QLabel(parent=self.home)
        self.label_28.setGeometry(QtCore.QRect(1320, 800, 121, 16))
        self.label_28.setStyleSheet("color: rgb(131, 131, 131);\n"
"background-color: none\n"
"")
        self.label_28.setObjectName("label_28")
        self.label_30 = QtWidgets.QLabel(parent=self.home)
        self.label_30.setGeometry(QtCore.QRect(1070, 840, 121, 16))
        self.label_30.setStyleSheet("color: rgb(131, 131, 131);\n"
"background-color: none\n"
"")
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(parent=self.home)
        self.label_31.setGeometry(QtCore.QRect(1370, 860, 121, 16))
        self.label_31.setStyleSheet("color: rgb(131, 131, 131);\n"
"background-color: none\n"
"")
        self.label_31.setObjectName("label_31")
        self.label_13 = QtWidgets.QLabel(parent=self.home)
        self.label_13.setGeometry(QtCore.QRect(0, 50, 981, 441))
        self.label_13.setStyleSheet("background-color: rgb(45, 45, 45); /* Màu đen */\n"
"    height: 50px; /* Chiều cao của thanh */\n"
"    width: 100%; /* Chiều rộng của thanh */\n"
"border-radius: 20px;")
        self.label_13.setText("")
        self.label_13.setScaledContents(True)
        self.label_13.setWordWrap(False)
        self.label_13.setObjectName("label_13")
        self.label_25 = QtWidgets.QLabel(parent=self.home)
        self.label_25.setGeometry(QtCore.QRect(70, 290, 121, 16))
        self.label_25.setStyleSheet("color: rgb(131, 131, 131);\n"
"background-color: none\n"
"")
        self.label_25.setObjectName("label_25")
        self.label_13.raise_()
        self.lineEdit_5.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_17.raise_()
        self.label_16.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.label_26.raise_()
        self.label_28.raise_()
        self.label_30.raise_()
        self.label_31.raise_()
        self.label_25.raise_()
        self.main_widget.addWidget(self.home)
        self.playlist = QtWidgets.QWidget()
        self.playlist.setObjectName("playlist")
        self.label_27 = QtWidgets.QLabel(parent=self.playlist)
        self.label_27.setGeometry(QtCore.QRect(10, 20, 981, 461))
        self.label_27.setStyleSheet("background-color: rgb(45, 45, 45); /* Màu đen */\n"
"    height: 50px; /* Chiều cao của thanh */\n"
"    width: 100%; /* Chiều rộng của thanh */\n"
"border-radius: 20px;")
        self.label_27.setText("")
        self.label_27.setScaledContents(True)
        self.label_27.setWordWrap(False)
        self.label_27.setObjectName("label_27")
        self.label_29 = QtWidgets.QLabel(parent=self.playlist)
        self.label_29.setGeometry(QtCore.QRect(40, 40, 211, 61))
        self.label_29.setStyleSheet("font: 26pt \"Segoe Print\";\n"
"background-color: none\n"
"")
        self.label_29.setObjectName("label_29")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.playlist)
        self.pushButton_7.setGeometry(QtCore.QRect(250, 50, 51, 51))
        self.pushButton_7.setStyleSheet("border: none;\n"
"background: none")
        self.pushButton_7.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/circle-play-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_7.setIcon(icon)
        self.pushButton_7.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.playlist)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(90, 150, 491, 336))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_46 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_46.setStyleSheet("background: none;\n"
"font: 16pt \"Segoe UI\";")
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_4.addWidget(self.label_46)
        self.label_32 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_32.setMaximumSize(QtCore.QSize(64, 64))
        self.label_32.setText("")
        self.label_32.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/unnamed.jpg"))
        self.label_32.setScaledContents(True)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_4.addWidget(self.label_32)
        self.label_48 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_48.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none")
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_4.addWidget(self.label_48)
        self.pushButton_13 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.pushButton_13.setStyleSheet("border: none;\n"
"background: none")
        self.pushButton_13.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/heart-regular.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_13.setIcon(icon1)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_4.addWidget(self.pushButton_13)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_36 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_36.setStyleSheet("background: none;\n"
"font: 16pt \"Segoe UI\";")
        self.label_36.setObjectName("label_36")
        self.horizontalLayout.addWidget(self.label_36)
        self.label_33 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_33.setMaximumSize(QtCore.QSize(64, 64))
        self.label_33.setText("")
        self.label_33.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/anhnhac.jpg"))
        self.label_33.setScaledContents(True)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout.addWidget(self.label_33)
        self.label_40 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_40.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none")
        self.label_40.setObjectName("label_40")
        self.horizontalLayout.addWidget(self.label_40)
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.pushButton_11.setStyleSheet("border: none;\n"
"background: none")
        self.pushButton_11.setText("")
        self.pushButton_11.setIcon(icon1)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout.addWidget(self.pushButton_11)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_37 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_37.setStyleSheet("background: none;\n"
"font: 16pt \"Segoe UI\";")
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_2.addWidget(self.label_37)
        self.label_34 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_34.setMaximumSize(QtCore.QSize(64, 64))
        self.label_34.setText("")
        self.label_34.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/anhnhac3.jpg"))
        self.label_34.setScaledContents(True)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_2.addWidget(self.label_34)
        self.label_41 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_41.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none")
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_2.addWidget(self.label_41)
        self.pushButton_12 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.pushButton_12.setStyleSheet("border: none;\n"
"background: none")
        self.pushButton_12.setText("")
        self.pushButton_12.setIcon(icon1)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_2.addWidget(self.pushButton_12)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_47 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_47.setStyleSheet("background: none;\n"
"font: 16pt \"Segoe UI\";")
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_5.addWidget(self.label_47)
        self.label_35 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_35.setMaximumSize(QtCore.QSize(64, 64))
        self.label_35.setAutoFillBackground(False)
        self.label_35.setText("")
        self.label_35.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/ab67616d0000b27343076111d560c6aec19bac01.jpg"))
        self.label_35.setScaledContents(True)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_5.addWidget(self.label_35)
        self.label_50 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_50.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none")
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_5.addWidget(self.label_50)
        self.pushButton_14 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.pushButton_14.setStyleSheet("border: none;\n"
"background: none")
        self.pushButton_14.setText("")
        self.pushButton_14.setIcon(icon1)
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_5.addWidget(self.pushButton_14)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalSlider = QtWidgets.QSlider(parent=self.playlist)
        self.verticalSlider.setGeometry(QtCore.QRect(941, 140, 20, 321))
        self.verticalSlider.setStyleSheet("background-color: white")
        self.verticalSlider.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.main_widget.addWidget(self.playlist)
        self.account = QtWidgets.QWidget()
        self.account.setObjectName("account")
        self.label_4 = QtWidgets.QLabel(parent=self.account)
        self.label_4.setGeometry(QtCore.QRect(470, 20, 151, 51))
        self.label_4.setStyleSheet("background-color: none;\n"
"font: 700 30pt \"Microsoft JhengHei UI\";\n"
"color: rgb(255, 255, 255)")
        self.label_4.setObjectName("label_4")
        self.txt_name = QtWidgets.QLineEdit(parent=self.account)
        self.txt_name.setGeometry(QtCore.QRect(300, 90, 221, 41))
        self.txt_name.setStyleSheet("width: 100%;\n"
"  padding: 10px;\n"
"  font-size: 14px;\n"
"  border: 1px solid #B3B3B3; \n"
"  border-radius: 20px; \n"
"background-color: rgb(255, 255, 255);\n"
"  color: rgb(0, 0, 0)")
        self.txt_name.setObjectName("txt_name")
        self.label_5 = QtWidgets.QLabel(parent=self.account)
        self.label_5.setGeometry(QtCore.QRect(80, 90, 111, 41))
        self.label_5.setStyleSheet("font: 14pt \"Segoe Print\";\n"
"background-color: none;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.account)
        self.label_6.setGeometry(QtCore.QRect(80, 130, 131, 91))
        self.label_6.setStyleSheet("font: 14pt \"Segoe Print\";\n"
"background-color: none;\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.account)
        self.label_7.setGeometry(QtCore.QRect(80, 220, 111, 41))
        self.label_7.setStyleSheet("font: 14pt \"Segoe Print\";\n"
"background-color: none;\n"
"")
        self.label_7.setObjectName("label_7")
        self.txt_email = QtWidgets.QLineEdit(parent=self.account)
        self.txt_email.setGeometry(QtCore.QRect(300, 160, 221, 41))
        self.txt_email.setStyleSheet("width: 100%;\n"
"  padding: 10px;\n"
"  font-size: 14px;\n"
"  border: 1px solid #B3B3B3; \n"
"  border-radius: 20px; \n"
"background-color: rgb(255, 255, 255);\n"
"  color: rgb(0, 0, 0)")
        self.txt_email.setObjectName("txt_email")
        self.label_8 = QtWidgets.QLabel(parent=self.account)
        self.label_8.setGeometry(QtCore.QRect(10, 20, 1001, 471))
        self.label_8.setStyleSheet("background-color: rgb(45, 45, 45); /* Màu đen */\n"
"    height: 50px; /* Chiều cao của thanh */\n"
"    width: 100%; /* Chiều rộng của thanh */\n"
"border-radius: 20px;")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.btn_upload = QtWidgets.QPushButton(parent=self.account)
        self.btn_upload.setGeometry(QtCore.QRect(870, 300, 41, 41))
        self.btn_upload.setStyleSheet("border-radius: 20px;\n"
"background: white;\n"
"")
        self.btn_upload.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/upload-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_upload.setIcon(icon2)
        self.btn_upload.setIconSize(QtCore.QSize(16, 18))
        self.btn_upload.setObjectName("btn_upload")
        self.label_12 = QtWidgets.QLabel(parent=self.account)
        self.label_12.setGeometry(QtCore.QRect(80, 290, 111, 41))
        self.label_12.setStyleSheet("font: 14pt \"Segoe Print\";\n"
"background-color: none;\n"
"")
        self.label_12.setObjectName("label_12")
        self.txt_gender = QtWidgets.QComboBox(parent=self.account)
        self.txt_gender.setGeometry(QtCore.QRect(300, 290, 221, 41))
        self.txt_gender.setStyleSheet("width: 100%;\n"
"  padding: 10px;\n"
"  font-size: 14px;\n"
"  border: 1px solid #B3B3B3; \n"
"  border-radius: 20px; \n"
"background-color: rgb(255, 255, 255);\n"
"  color: rgb(0, 0, 0)")
        self.txt_gender.setObjectName("txt_gender")
        self.txt_gender.addItem("")
        self.txt_gender.addItem("")
        self.txt_gender.addItem("")
        self.txt_gender.addItem("")
        self.txt_dob = QtWidgets.QDateEdit(parent=self.account)
        self.txt_dob.setGeometry(QtCore.QRect(300, 220, 221, 41))
        self.txt_dob.setStyleSheet("width: 100%;\n"
"  padding: 10px;\n"
"  font-size: 14px;\n"
"  border: 1px solid #B3B3B3; \n"
"  border-radius: 20px; \n"
"background-color: rgb(255, 255, 255);\n"
"  color: rgb(0, 0, 0)")
        self.txt_dob.setObjectName("txt_dob")
        self.lb_avatar = QtWidgets.QLabel(parent=self.account)
        self.lb_avatar.setGeometry(QtCore.QRect(620, 80, 241, 261))
        self.lb_avatar.setStyleSheet("border-radius: 30px;\n"
"background: white;\n"
"")
        self.lb_avatar.setText("")
        self.lb_avatar.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/user-solid.svg"))
        self.lb_avatar.setScaledContents(True)
        self.lb_avatar.setObjectName("lb_avatar")
        self.btn_save = QtWidgets.QPushButton(parent=self.account)
        self.btn_save.setGeometry(QtCore.QRect(460, 370, 80, 24))
        self.btn_save.setObjectName("btn_save")
        self.label_8.raise_()
        self.label_4.raise_()
        self.txt_name.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.txt_email.raise_()
        self.btn_upload.raise_()
        self.label_12.raise_()
        self.txt_gender.raise_()
        self.txt_dob.raise_()
        self.lb_avatar.raise_()
        self.btn_save.raise_()
        self.main_widget.addWidget(self.account)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 51, 471))
        self.label_2.setStyleSheet("background-color: rgb(40, 40, 40); /* Màu đen */\n"
"    height: 50px; /* Chiều cao của thanh */\n"
"    width: 100%; /* Chiều rộng của thanh */\n"
"border-radius: 20px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 500, 1081, 121))
        self.widget.setStyleSheet("background-color: rgb(59, 59, 59)")
        self.widget.setObjectName("widget")
        self.label_9 = QtWidgets.QLabel(parent=self.widget)
        self.label_9.setGeometry(QtCore.QRect(30, 30, 70, 70))
        self.label_9.setAutoFillBackground(False)
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/ab67616d0000b27343076111d560c6aec19bac01.jpg"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(parent=self.widget)
        self.label_11.setGeometry(QtCore.QRect(110, 60, 121, 16))
        self.label_11.setStyleSheet("color: rgb(131, 131, 131);")
        self.label_11.setObjectName("label_11")
        self.label_10 = QtWidgets.QLabel(parent=self.widget)
        self.label_10.setGeometry(QtCore.QRect(110, 40, 91, 16))
        self.label_10.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_10.setObjectName("label_10")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(180, 40, 80, 24))
        self.pushButton_4.setStyleSheet("border: none;\n"
"background: none")
        self.pushButton_4.setText("")
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton.setGeometry(QtCore.QRect(500, 10, 101, 81))
        self.pushButton.setStyleSheet("border: none;\n"
"background: none")
        self.pushButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/circle-play-regular.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon3)
        self.pushButton.setIconSize(QtCore.QSize(32, 32))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(420, 40, 80, 24))
        self.pushButton_2.setStyleSheet("border: none;\n"
"background: none")
        self.pushButton_2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/backward-step-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon4)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(600, 40, 80, 24))
        self.pushButton_3.setStyleSheet("border: none;\n"
"background: none")
        self.pushButton_3.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/forward-step-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_3.setIcon(icon5)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_5.setGeometry(QtCore.QRect(890, 60, 21, 24))
        self.pushButton_5.setStyleSheet("border: none;\n"
"background: none\n"
"")
        self.pushButton_5.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/volume-high-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_5.setIcon(icon6)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalSlider_2 = QtWidgets.QSlider(parent=self.widget)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(920, 60, 121, 20))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider = QtWidgets.QSlider(parent=self.widget)
        self.horizontalSlider.setGeometry(QtCore.QRect(320, 70, 441, 20))
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalWidget.setGeometry(QtCore.QRect(20, 40, 41, 151))
        self.verticalWidget.setStyleSheet("background-color: none")
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_nav_account = QtWidgets.QPushButton(parent=self.verticalWidget)
        self.btn_nav_account.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_nav_account.setStyleSheet("background: white;\n"
" border-radius: 15px;")
        self.btn_nav_account.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/user-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_nav_account.setIcon(icon7)
        self.btn_nav_account.setIconSize(QtCore.QSize(16, 16))
        self.btn_nav_account.setObjectName("btn_nav_account")
        self.verticalLayout.addWidget(self.btn_nav_account)
        self.btn_nav_home = QtWidgets.QPushButton(parent=self.verticalWidget)
        self.btn_nav_home.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_nav_home.setStyleSheet("background: white;\n"
" border-radius: 15px\n"
"")
        self.btn_nav_home.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/house-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_nav_home.setIcon(icon8)
        self.btn_nav_home.setObjectName("btn_nav_home")
        self.verticalLayout.addWidget(self.btn_nav_home)
        self.btn_nav_playlist = QtWidgets.QPushButton(parent=self.verticalWidget)
        self.btn_nav_playlist.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_nav_playlist.setStyleSheet("background: white;\n"
" border-radius: 15px\n"
"")
        self.btn_nav_playlist.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/list-solid123.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_nav_playlist.setIcon(icon9)
        self.btn_nav_playlist.setObjectName("btn_nav_playlist")
        self.verticalLayout.addWidget(self.btn_nav_playlist)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.main_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Popular Songs"))
        self.label_18.setText(_translate("MainWindow", "Dù cho tận thế"))
        self.label_19.setText(_translate("MainWindow", "Wrong times"))
        self.label_20.setText(_translate("MainWindow", "APT"))
        self.label_21.setText(_translate("MainWindow", "Mất kết nối"))
        self.label_22.setText(_translate("MainWindow", "Puppy, Dangrangto"))
        self.label_23.setText(_translate("MainWindow", "ROSÉ, Bruno Mars"))
        self.label_24.setText(_translate("MainWindow", "Dương Domic"))
        self.label_26.setText(_translate("MainWindow", "Puppy & Dangrangto"))
        self.label_28.setText(_translate("MainWindow", "Puppy & Dangrangto"))
        self.label_30.setText(_translate("MainWindow", "Puppy & Dangrangto"))
        self.label_31.setText(_translate("MainWindow", "Puppy & Dangrangto"))
        self.label_25.setText(_translate("MainWindow", "Erik"))
        self.label_29.setText(_translate("MainWindow", "My playlist"))
        self.label_46.setText(_translate("MainWindow", "1"))
        self.label_48.setText(_translate("MainWindow", "Dù cho tận thế"))
        self.label_36.setText(_translate("MainWindow", "2"))
        self.label_40.setText(_translate("MainWindow", "Mất kết nối"))
        self.label_37.setText(_translate("MainWindow", "3"))
        self.label_41.setText(_translate("MainWindow", "Mất kết nối"))
        self.label_47.setText(_translate("MainWindow", "4"))
        self.label_50.setText(_translate("MainWindow", "Wrong times"))
        self.label_4.setText(_translate("MainWindow", "Profile"))
        self.txt_name.setPlaceholderText(_translate("MainWindow", "Name"))
        self.label_5.setText(_translate("MainWindow", "Name:"))
        self.label_6.setText(_translate("MainWindow", "Email:"))
        self.label_7.setText(_translate("MainWindow", "Birthday:"))
        self.txt_email.setPlaceholderText(_translate("MainWindow", "Email"))
        self.label_12.setText(_translate("MainWindow", "Gender:"))
        self.txt_gender.setItemText(0, _translate("MainWindow", "None"))
        self.txt_gender.setItemText(1, _translate("MainWindow", "Male"))
        self.txt_gender.setItemText(2, _translate("MainWindow", "Female"))
        self.txt_gender.setItemText(3, _translate("MainWindow", "Other"))
        self.txt_dob.setDisplayFormat(_translate("MainWindow", "d/M/yy"))
        self.btn_save.setText(_translate("MainWindow", "Save"))
        self.label_11.setText(_translate("MainWindow", "Puppy, Dangrangto"))
        self.label_10.setText(_translate("MainWindow", "Wrong times"))
