# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/playlist.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PlaylistItem(object):
    def setupUi(self, PlaylistItem):
        PlaylistItem.setObjectName("PlaylistItem")
        PlaylistItem.setMinimumSize(QtCore.QSize(0, 56))
        self.horizontalLayout = QtWidgets.QHBoxLayout(PlaylistItem)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_img = QtWidgets.QLabel(parent=PlaylistItem)
        self.lbl_img.setMinimumSize(QtCore.QSize(48, 48))
        self.lbl_img.setMaximumSize(QtCore.QSize(48, 48))
        self.lbl_img.setScaledContents(True)
        self.lbl_img.setStyleSheet("border-radius: 6px; background: #222;")
        self.lbl_img.setObjectName("lbl_img")
        self.horizontalLayout.addWidget(self.lbl_img)
        self.lbl_name = QtWidgets.QLabel(parent=PlaylistItem)
        self.lbl_name.setStyleSheet("color: #fff; font-size: 10.5pt; font-weight: bold; background: none; margin-left: 8px;")
        self.lbl_name.setMinimumWidth(100)
        self.lbl_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignVCenter|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.lbl_name.setObjectName("lbl_name")
        self.horizontalLayout.addWidget(self.lbl_name)
        self.lbl_artist = QtWidgets.QLabel(parent=PlaylistItem)
        self.lbl_artist.setStyleSheet("color: #b3b3b3; font-size: 9pt; background: none; margin-left: 8px;")
        self.lbl_artist.setMinimumWidth(80)
        self.lbl_artist.setAlignment(QtCore.Qt.AlignmentFlag.AlignVCenter|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.lbl_artist.setObjectName("lbl_artist")
        self.horizontalLayout.addWidget(self.lbl_artist)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_play = QtWidgets.QPushButton(parent=PlaylistItem)
        self.btn_play.setStyleSheet("background: none; border: none;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/circle-play-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_play.setIcon(icon)
        self.btn_play.setIconSize(QtCore.QSize(22, 22))
        self.btn_play.setText("")
        self.btn_play.setObjectName("btn_play")
        self.horizontalLayout.addWidget(self.btn_play)
        self.btn_delete = QtWidgets.QPushButton(parent=PlaylistItem)
        self.btn_delete.setStyleSheet("background: none; border: none; color: #ff4d4f; font-weight: bold; font-size: 10pt; padding: 2px 10px; margin-left: 6px;")
        self.btn_delete.setObjectName("btn_delete")
        self.horizontalLayout.addWidget(self.btn_delete)

        self.retranslateUi(PlaylistItem)
        QtCore.QMetaObject.connectSlotsByName(PlaylistItem)

    def retranslateUi(self, PlaylistItem):
        _translate = QtCore.QCoreApplication.translate
        self.btn_delete.setText(_translate("PlaylistItem", "Xoá"))
