# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/register.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(310, 0, 631, 571))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_7 = QtWidgets.QLabel(parent=self.page)
        self.label_7.setGeometry(QtCore.QRect(90, 10, 141, 51))
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 25pt \"Segoe Print\";")
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(parent=self.page)
        self.label_5.setGeometry(QtCore.QRect(230, 10, 51, 51))
        self.label_5.setAutoFillBackground(False)
        self.label_5.setStyleSheet("background: none;\n"
"    border: none;")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../../../../Downloads/corporate_Music-Flex-Icons-03.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_14 = QtWidgets.QLabel(parent=self.page)
        self.label_14.setGeometry(QtCore.QRect(40, 10, 321, 481))
        self.label_14.setStyleSheet("width: 100%;\n"
"    height: 100%;\n"
"    background-color: rgba(0, 0, 0, 0.5); /* Nền đen với độ trong suốt 50% */\n"
"    display: flex;\n"
"    justify-content: center;\n"
"    align-items: center;\n"
"border-radius: 20px")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_3 = QtWidgets.QLabel(parent=self.page)
        self.label_3.setGeometry(QtCore.QRect(230, 10, 51, 51))
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("background: none;\n"
"    border: none;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/corporate_Music-Flex-Icons-03.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.btn_eye_cp = QtWidgets.QPushButton(parent=self.page)
        self.btn_eye_cp.setGeometry(QtCore.QRect(280, 370, 80, 24))
        self.btn_eye_cp.setStyleSheet("border: none;\n"
"background: none")
        self.btn_eye_cp.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/eye-slash-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_eye_cp.setIcon(icon)
        self.btn_eye_cp.setObjectName("btn_eye_cp")
        self.btn_eye_p = QtWidgets.QPushButton(parent=self.page)
        self.btn_eye_p.setGeometry(QtCore.QRect(280, 280, 80, 24))
        self.btn_eye_p.setStyleSheet("border: none;\n"
"background: none")
        self.btn_eye_p.setText("")
        self.btn_eye_p.setIcon(icon)
        self.btn_eye_p.setObjectName("btn_eye_p")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.page)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 50, 281, 471))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_8 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 15pt \"Segoe Print\";")
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.txt_email = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.txt_email.setStyleSheet("width: 100%;\n"
"  padding: 10px;\n"
"  font-size: 14px;\n"
"  border: 1px solid #B3B3B3; \n"
"  border-radius: 20px; \n"
"  background-color: transparent;\n"
"  color: rgb(0, 0, 0)")
        self.txt_email.setText("")
        self.txt_email.setDragEnabled(True)
        self.txt_email.setObjectName("txt_email")
        self.verticalLayout.addWidget(self.txt_email)
        self.label_9 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 15pt \"Segoe Print\";")
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.txt_name = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.txt_name.setStyleSheet("width: 100%;\n"
"  padding: 10px;\n"
"  font-size: 14px;\n"
"  border: 1px solid #B3B3B3; \n"
"  border-radius: 20px; \n"
"  background-color: transparent;\n"
"  color: rgb(0, 0, 0) ")
        self.txt_name.setText("")
        self.txt_name.setObjectName("txt_name")
        self.verticalLayout.addWidget(self.txt_name)
        self.label_11 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_11.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 15pt \"Segoe Print\";")
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.txt_password = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.txt_password.setStyleSheet("width: 100%;\n"
"  padding: 10px;\n"
"  font-size: 14px;\n"
"  border: 1px solid #B3B3B3; \n"
"  border-radius: 20px; \n"
"  background-color: transparent;\n"
"  color: rgb(0, 0, 0)")
        self.txt_password.setText("")
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_password.setObjectName("txt_password")
        self.verticalLayout.addWidget(self.txt_password)
        self.label_10 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 15pt \"Segoe Print\";")
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.txt_conf_pwd = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.txt_conf_pwd.setStyleSheet("width: 100%;\n"
"  padding: 10px;\n"
"  font-size: 14px;\n"
"  border: 1px solid #B3B3B3; \n"
"  border-radius: 20px; \n"
"  background-color: transparent;\n"
"  color: rgb(0, 0, 0)")
        self.txt_conf_pwd.setText("")
        self.txt_conf_pwd.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_conf_pwd.setObjectName("txt_conf_pwd")
        self.verticalLayout.addWidget(self.txt_conf_pwd)
        self.btn_register = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.btn_register.setStyleSheet("background: qlineargradient( spread: pad, x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #fff9b0, stop: 1 #041f60 );\n"
"font: 9pt \"Segoe Print\";\n"
"border: 2px solid #8A2BE2; /* Viền màu tím nhạt hơn */\n"
" color: white; /* Màu chữ trắng */\n"
" padding: 10px 20px; \n"
"text-align: center; \n"
"text-decoration: none; \n"
"display: inline-block;\n"
" font-size: 16px; \n"
"margin: 4px 2px; \n"
"cursor: pointer;\n"
"border-radius: 20px; /* Cạnh bo tròn */ \n"
"box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19); /* Đổ bóng */\n"
"transition: all 0.3s ease; /* Hiệu ứng chuyển đổi */")
        self.btn_register.setObjectName("btn_register")
        self.verticalLayout.addWidget(self.btn_register)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton_4.setStyleSheet("padding: 10px;\n"
"font-size: 14px;\n"
"border-radius: 20px; \n"
"background-color: transparent;\n"
"color:rgb(0, 0, 0);\n"
"font: 9pt \"Segoe Print\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.btn_login = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.btn_login.setStyleSheet("border-radius: 15px;\n"
"font: 9pt \"Segoe Print\";\n"
"color: rgb(255, 0, 0)")
        self.btn_login.setObjectName("btn_login")
        self.horizontalLayout.addWidget(self.btn_login)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_14.raise_()
        self.label_7.raise_()
        self.label_5.raise_()
        self.label_3.raise_()
        self.verticalLayoutWidget.raise_()
        self.btn_eye_cp.raise_()
        self.btn_eye_p.raise_()
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget.addWidget(self.page_3)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -40, 851, 561))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("width: 100%;\n"
"    height: 100%;\n"
"    background-color: rgba(0, 0, 0, 0.5); /* Nền đen với độ trong suốt 50% */\n"
"    display: flex;\n"
"    justify-content: center;\n"
"    align-items: center;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/hinh-nen-slide-dep-chu-de-am-nhac-de-thuong.jpg"))
        self.label.setScaledContents(True)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.label_12 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(0, 70, 361, 471))
        self.label_12.setStyleSheet("height: 100%;\n"
"    background-color: rgba(0, 0, 0,); /* Nền đen với độ trong suốt 50% */\n"
"    display: flex;\n"
"    justify-content: center;\n"
"    align-items: center;\n"
"border-radius: 20px;")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label.raise_()
        self.stackedWidget.raise_()
        self.label_12.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "Sign Up"))
        self.label_8.setText(_translate("MainWindow", "Email:"))
        self.txt_email.setPlaceholderText(_translate("MainWindow", "Email"))
        self.label_9.setText(_translate("MainWindow", "Name:"))
        self.txt_name.setPlaceholderText(_translate("MainWindow", "Name"))
        self.label_11.setText(_translate("MainWindow", "Password:"))
        self.txt_password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.label_10.setText(_translate("MainWindow", "Confirm password:"))
        self.txt_conf_pwd.setPlaceholderText(_translate("MainWindow", "Confirm Password"))
        self.btn_register.setText(_translate("MainWindow", "Sign Up"))
        self.pushButton_4.setText(_translate("MainWindow", "Have an account already? "))
        self.btn_login.setText(_translate("MainWindow", "Sign In"))
