# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/song.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(191, 201)
        Form.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius: 20px\n"
"")
        self.lbl_image = QtWidgets.QLabel(parent=Form)
        self.lbl_image.setGeometry(QtCore.QRect(20, 10, 151, 151))
        self.lbl_image.setText("")
        self.lbl_image.setObjectName("lbl_image")
        self.lbl_name = QtWidgets.QLabel(parent=Form)
        self.lbl_name.setGeometry(QtCore.QRect(10, 170, 81, 16))
        self.lbl_name.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none")
        self.lbl_name.setText("")
        self.lbl_name.setObjectName("lbl_name")
        self.lbl_artist = QtWidgets.QLabel(parent=Form)
        self.lbl_artist.setGeometry(QtCore.QRect(10, 183, 81, 16))
        self.lbl_artist.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none")
        self.lbl_artist.setText("")
        self.lbl_artist.setObjectName("lbl_artist")
        self.btn_add = QtWidgets.QPushButton(parent=Form)
        self.btn_add.setGeometry(QtCore.QRect(100, 170, 31, 24))
        self.btn_add.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/heart-regular.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_add.setIcon(icon)
        self.btn_add.setObjectName("btn_add")
        self.btn_play = QtWidgets.QPushButton(parent=Form)
        self.btn_play.setGeometry(QtCore.QRect(140, 165, 31, 31))
        self.btn_play.setMinimumSize(QtCore.QSize(0, 24))
        self.btn_play.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/circle-play-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_play.setIcon(icon1)
        self.btn_play.setIconSize(QtCore.QSize(30, 30))
        self.btn_play.setObjectName("btn_play")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
