# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/song.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(191, 201)
        Form.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius: 20px\n"
"")
        self.lb_pic = QtWidgets.QLabel(parent=Form)
        self.lb_pic.setGeometry(QtCore.QRect(20, 10, 151, 151))
        self.lb_pic.setText("")
        self.lb_pic.setObjectName("lb_pic")
        self.lb_songname = QtWidgets.QLabel(parent=Form)
        self.lb_songname.setGeometry(QtCore.QRect(10, 170, 81, 16))
        self.lb_songname.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none")
        self.lb_songname.setText("")
        self.lb_songname.setObjectName("lb_songname")
        self.lb_athname = QtWidgets.QLabel(parent=Form)
        self.lb_athname.setGeometry(QtCore.QRect(10, 183, 81, 16))
        self.lb_athname.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none")
        self.lb_athname.setText("")
        self.lb_athname.setObjectName("lb_athname")
        self.bt_like = QtWidgets.QPushButton(parent=Form)
        self.bt_like.setGeometry(QtCore.QRect(100, 170, 31, 24))
        self.bt_like.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/heart-regular.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_like.setIcon(icon)
        self.bt_like.setObjectName("bt_like")
        self.bt_start = QtWidgets.QPushButton(parent=Form)
        self.bt_start.setGeometry(QtCore.QRect(140, 165, 31, 31))
        self.bt_start.setMinimumSize(QtCore.QSize(0, 24))
        self.bt_start.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/circle-play-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_start.setIcon(icon1)
        self.bt_start.setIconSize(QtCore.QSize(30, 30))
        self.bt_start.setObjectName("bt_start")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
