# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/song.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(191, 201)
        Form.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius: 20px\n"
"")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(20, 10, 151, 151))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_21 = QtWidgets.QLabel(parent=Form)
        self.label_21.setGeometry(QtCore.QRect(10, 170, 81, 16))
        self.label_21.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none")
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(parent=Form)
        self.label_22.setGeometry(QtCore.QRect(10, 183, 81, 16))
        self.label_22.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none")
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(100, 170, 31, 24))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/heart-regular.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 165, 31, 31))
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 24))
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TriHung/pythonapp/ui/../img/circle-play-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
